[package]
name = "bitcoin-rs-mining"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
description = "bitcoin-rs :: mining"

[lints]
workspace = true

[dependencies]
bitcoin-rs-primitives.workspace = true
bitcoin-rs-consensus.workspace = true
bitcoin-rs-script.workspace = true
bitcoin-rs-chain.workspace = true
bitcoin-rs-mempool.workspace = true
compact_str.workspace = true
thiserror.workspace = true

[features]
default = []
rocksdb = []
fjall = []
redb = []
mdbx = []

[dev-dependencies]
proptest.workspace = true
bitcoin.workspace = true
criterion.workspace = true

[[bench]]
name = "candidate"
harness = false
