//! Cross-version snapshot fidelity: a file written by the **previous** record
//! codec must still load to the same consensus values, and the current build
//! must still write the same bytes for the same logical set.
//!
//! `snapshot_roundtrip.rs` writes and reads in one process, so it passes even
//! if both sides change together — which is precisely the failure a record
//! layout change can cause. `fixtures/utxo-v4-golden.dat` was generated by a
//! build of the v4 codec and is committed as bytes, so the assertion here has
//! a fixed point outside this build.
//!
//! `hash_serialized_3` and the `MuHash` trailer are computed over decoded
//! consensus values, never over the in-memory encoding. That is the invariant
//! the whole record-layout change rests on, and it is the one asserted here.
// A golden-vector test that cannot read its own fixture has failed; panicking
// names the step that broke.
#![allow(clippy::expect_used)]

use std::io::Cursor;

use bitcoin::{Amount, ScriptBuf};
use bitcoin_rs_primitives::{Hash256, OutPoint, TxOut};
use bitcoin_rs_utxo::{
    BlockChanges, UtxoAdd, UtxoSet, hash_serialized_3, read_snapshot, write_snapshot,
};

/// A v4-codec build's snapshot of [`golden_fixture`].
const GOLDEN: &[u8] = include_bytes!("fixtures/utxo-v4-golden.dat");

/// `hash_serialized_3` of that set, as the v4 build computed it.
const GOLDEN_HASH_HEX: &str = "020e5a59271f9db60e11102c4262702747676e868e80e7837b6e6d5fb05213ff";

const GOLDEN_OUTPUTS: usize = 433;
const GOLDEN_TIP_HEIGHT: u32 = 412_732;

fn txid(seed: u64) -> Hash256 {
    let mut bytes = [0_u8; 32];
    bytes[..8].copy_from_slice(&seed.to_le_bytes());
    bytes[8..16].copy_from_slice(&seed.rotate_left(23).to_le_bytes());
    bytes[16..24].copy_from_slice(&seed.wrapping_mul(0x94d0_49bb_1331_11eb).to_le_bytes());
    bytes[24..32].copy_from_slice(&seed.wrapping_add(0x0123_4567_89ab_cdef).to_le_bytes());
    Hash256::from_le_bytes(&bytes)
}

fn hex(bytes: &[u8]) -> String {
    use core::fmt::Write as _;
    bytes.iter().fold(String::new(), |mut out, byte| {
        let _ = write!(out, "{byte:02x}");
        out
    })
}

/// Rebuilds the exact set the golden vector was generated from.
///
/// Kept verbatim beside the fixture so its provenance is in the tree rather
/// than in a commit message: this function *is* the generator. A deliberately
/// awkward mix — every field width the record codec can choose between, and
/// every partition boundary it can straddle.
fn golden_fixture() -> UtxoSet {
    let set = UtxoSet::new();
    let mut changes = BlockChanges::default();

    for seed in 0_u64..120 {
        for vout in 0..=(seed % 6) {
            let script: Vec<u8> = match seed % 4 {
                0 => [&[0x00, 0x14][..], &[0xAB; 20][..]].concat(),
                1 => [&[0x76, 0xa9, 0x14][..], &[0xCD; 20][..], &[0x88, 0xac][..]].concat(),
                2 => [&[0xa9, 0x14][..], &[0xEF; 20][..], &[0x87][..]].concat(),
                _ => [&[0x51, 0x20][..], &[0x12; 32][..]].concat(),
            };
            // Round amounts, awkward amounts, zero and the money supply: the
            // cases Core's amount transform treats differently.
            let value = match seed % 5 {
                0 => 0,
                1 => 50 * 100_000_000,
                2 => 1,
                3 => 21_000_000 * 100_000_000,
                _ => seed.wrapping_mul(7_919).wrapping_add(54_321),
            };
            changes.add(UtxoAdd::new(
                OutPoint::new(txid(seed), u32::try_from(vout).unwrap_or(0)),
                TxOut {
                    value: Amount::from_sat(value),
                    script_pubkey: ScriptBuf::from_bytes(script),
                },
                seed % 11 == 0,
                u32::try_from(seed).unwrap_or(0) * 137,
            ));
        }
    }

    // Past the inline partition and past the vout bitmap, so overflow ordering
    // is pinned too.
    let wide = txid(900_001);
    for vout in [0_u32, 1, 7, 8, 9, 63, 64, 65, 1_000, 70_000, u32::MAX] {
        changes.add(UtxoAdd::new(
            OutPoint::new(wide, vout),
            TxOut {
                value: Amount::from_sat(u64::from(vout) + 1),
                script_pubkey: ScriptBuf::from_bytes(vec![0x51; 22]),
            },
            false,
            840_000,
        ));
    }

    // The two ends of the script length range.
    changes.add(UtxoAdd::new(
        OutPoint::new(txid(900_002), 0),
        TxOut {
            value: Amount::from_sat(7),
            script_pubkey: ScriptBuf::from_bytes(Vec::new()),
        },
        true,
        1,
    ));
    changes.add(UtxoAdd::new(
        OutPoint::new(txid(900_003), 0),
        TxOut {
            value: Amount::from_sat(u64::MAX),
            script_pubkey: ScriptBuf::from_bytes(vec![0xAB; 2_048]),
        },
        false,
        u32::MAX >> 1,
    ));

    set.commit_block(&changes, &txid(1_234_567))
        .expect("fixture commits");
    set
}

/// The load direction: v4 bytes must still decode to the same consensus values.
#[test]
fn a_v4_snapshot_loads_to_the_hash_and_trailer_it_was_written_with() {
    let loaded = read_snapshot(&mut Cursor::new(GOLDEN)).expect("v4 snapshot loads");

    assert_eq!(loaded.height, GOLDEN_TIP_HEIGHT);
    assert_eq!(loaded.tip_hash, txid(4_242));
    assert_eq!(loaded.set.len(), GOLDEN_OUTPUTS, "output count drifted");
    assert_eq!(
        loaded.muhash_trailer, [0_u8; 384],
        "the MuHash trailer must survive the load byte for byte"
    );
    assert_eq!(
        hex(&hash_serialized_3(&loaded.set).expect("hash").to_le_bytes()),
        GOLDEN_HASH_HEX,
        "a v4 snapshot no longer hashes to what the v4 build computed"
    );
}

/// The write direction: the same logical set must still serialize identically.
///
/// Stronger than the load test, because the snapshot writer emits records and
/// their outputs in the order the record layout stores them. A pure reordering
/// would show up here and nowhere else — `hash_serialized_3` sorts by
/// `(txid, vout)` before hashing, so it cannot see one.
#[test]
fn the_current_build_writes_the_bytes_the_v4_build_wrote() {
    let set = golden_fixture();
    let mut bytes = Vec::new();
    write_snapshot(&set, &txid(4_242), GOLDEN_TIP_HEIGHT, &mut bytes).expect("write");

    assert_eq!(
        bytes.len(),
        GOLDEN.len(),
        "snapshot length changed: {} against the v4 build's {}",
        bytes.len(),
        GOLDEN.len()
    );
    assert!(
        bytes == GOLDEN,
        "snapshot bytes diverged from the v4 build at offset {:?}",
        bytes.iter().zip(GOLDEN).position(|(a, b)| a != b)
    );
}

/// Round-tripping the golden file through this build must be a fixed point.
#[test]
fn reloading_and_rewriting_a_v4_snapshot_reproduces_it_exactly() {
    let loaded = read_snapshot(&mut Cursor::new(GOLDEN)).expect("v4 snapshot loads");
    let mut rewritten = Vec::new();
    write_snapshot(&loaded.set, &loaded.tip_hash, loaded.height, &mut rewritten).expect("rewrite");

    assert!(
        rewritten == GOLDEN,
        "a load/store cycle is not a fixed point; first difference at {:?}",
        rewritten.iter().zip(GOLDEN).position(|(a, b)| a != b)
    );
}
