# Standalone generated platform header; algorithm constants remain in unmodified Core sources.
set(HAVE_DECL_FORK 1)
set(HAVE_IFADDRS 1)
set(HAVE_DECL_PIPE2 1)
set(HAVE_DECL_SETSID 1)
set(HAVE_FDATASYNC 1)
set(HAVE_GETENTROPY_RAND 1)
set(HAVE_GETRANDOM 1)
set(HAVE_MALLOC_INFO 1)
set(HAVE_MALLOPT_ARENA_MAX 1)
set(HAVE_O_CLOEXEC 1)
set(HAVE_POSIX_FALLOCATE 1)
set(HAVE_SOCKADDR_UN 1)
set(HAVE_STRONG_GETAUXVAL 1)
set(HAVE_SYSTEM 1)
set(STRERROR_R_CHAR_P 1)
set(CLIENT_NAME "Bitcoin Core")
set(CLIENT_VERSION_MAJOR 31)
set(CLIENT_VERSION_MINOR 1)
set(CLIENT_VERSION_BUILD 0)
set(CLIENT_VERSION_IS_RELEASE "true")
set(COPYRIGHT_YEAR "2026")
set(COPYRIGHT_HOLDERS "The %s developers")
set(COPYRIGHT_HOLDERS_FINAL "The ${CLIENT_NAME} developers")
set(CLIENT_BUGREPORT "https://github.com/bitcoin/bitcoin/issues")
set(CLIENT_VERSION_STRING "31.1.0")
set(PROJECT_HOMEPAGE_URL "https://bitcoincore.org/")
if(NOT DEFINED CORE_ROOT OR "${CORE_ROOT}" STREQUAL "" OR
   NOT DEFINED ORACLE_OUTPUT OR "${ORACLE_OUTPUT}" STREQUAL "")
  message(FATAL_ERROR "Supply non-empty CORE_ROOT and ORACLE_OUTPUT")
endif()
file(MAKE_DIRECTORY "${ORACLE_OUTPUT}/src")
configure_file("${CORE_ROOT}/cmake/bitcoin-build-config.h.in" "${ORACLE_OUTPUT}/src/bitcoin-build-config.h")
file(WRITE "${ORACLE_OUTPUT}/src/bitcoin-build-info.h" "#define BUILD_GIT_TAG \"v31.1\"\n")
