[package]
name = "bitcoin-rs-p2p"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
repository.workspace = true
description = "bitcoin-rs :: p2p"

[lints]
workspace = true

[features]
default = ["fjall"]
rocksdb = ["bitcoin-rs-storage/rocksdb"]
fjall = ["bitcoin-rs-storage/fjall"]
redb = ["bitcoin-rs-storage/redb"]

[dependencies]
bitcoin-rs-chain.workspace = true
bitcoin-rs-primitives.workspace = true
bitcoin-rs-storage = { workspace = true, default-features = false }
bitcoin.workspace = true
bytes.workspace = true
crossbeam-channel.workspace = true
parking_lot.workspace = true
arc-swap.workspace = true
bytemuck.workspace = true
zerocopy.workspace = true
tinyvec.workspace = true
smallvec.workspace = true
hashbrown.workspace = true
thiserror.workspace = true
tracing.workspace = true
metrics.workspace = true
sha2.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true
tempfile = ">=3.20.0, <4"
serde_json.workspace = true

[[bench]]
name = "write_message"
harness = false
